services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata1:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5433:5432
  
  db2:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind_final
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata2:/var/lib/postgresql/data
      - ./data/output/northwind_final.sql:/docker-entrypoint-initdb.d/northwind_final.sql
    ports:
      - 5434:5432